package com.periodic.app;
import android.content.*;import android.graphics.*;import android.view.*;
public final class ExploreView extends View {
 private final Element e;private final Paint p=new Paint(Paint.ANTI_ALIAS_FLAG|Paint.DITHER_FLAG);private float phase=0;private final RectF scaleButton=new RectF();
 public ExploreView(Context c,Element e){super(c);this.e=e;setLayerType(View.LAYER_TYPE_SOFTWARE,null);p.setTypeface(Typeface.create("sans",Typeface.BOLD));}
 @Override public boolean onTouchEvent(MotionEvent m){if(m.getAction()==MotionEvent.ACTION_UP&&scaleButton.contains(m.getX(),m.getY())){getContext().startActivity(new Intent(getContext(),ScaleJourneyActivity.class));return true;}return true;}
 @Override protected void onDraw(Canvas c){c.drawColor(Color.rgb(4,9,13));float sx=getWidth()/1600f,sy=getHeight()/900f;c.save();c.scale(sx,sy);draw(c);c.restore();phase=(phase+.45f)%360;postInvalidateOnAnimation();}
 private void draw(Canvas c){int accent=Visuals.categoryColor(e.category);p.setShader(new RadialGradient(250,270,310,new int[]{Color.argb(80,Color.red(accent),Color.green(accent),Color.blue(accent)),Color.TRANSPARENT},null,Shader.TileMode.CLAMP));c.drawRect(0,0,1600,900,p);p.setShader(null);p.setColor(Color.WHITE);p.setTextSize(38);p.setTextAlign(Paint.Align.LEFT);c.drawText(e.name+" Deep Dive",45,58,p);p.setColor(Color.rgb(158,203,215));p.setTextSize(15);c.drawText("Isotopes • ions • compounds • occurrence • evidence",47,86,p);drawNucleus(c,270,300,150);drawIsotopes(c,500,120,1015,475);drawChemistry(c,1045,120,1555,475);drawKnowledge(c,500,500,1555,820);scaleButton.set(getWidth()*.045f,getHeight()*.79f,getWidth()*.26f,getHeight()*.91f);RectF b=new RectF(70,715,420,820);p.setColor(Color.rgb(27,87,105));c.drawRoundRect(b,22,22,p);p.setStyle(Paint.Style.STROKE);p.setStrokeWidth(2);p.setColor(Color.rgb(116,211,229));c.drawRoundRect(b,22,22,p);p.setStyle(Paint.Style.FILL);p.setTextAlign(Paint.Align.CENTER);p.setColor(Color.WHITE);p.setTextSize(21);c.drawText("START SCALE JOURNEY",b.centerX(),b.centerY()+7,p);}
 private void drawNucleus(Canvas c,float cx,float cy,float r){p.setTextAlign(Paint.Align.CENTER);p.setColor(Color.rgb(226,210,154));p.setTextSize(20);c.drawText(e.isotopeLabel()+" nucleus",cx,cy-r-25,p);int A=e.representativeMassNumber(),Z=e.number;float dot=Math.max(2.2f,Math.min(8f,115f/(float)Math.sqrt(A)));for(int i=0;i<A;i++){double a=i*2.399963+phase*.001;float rr=(float)Math.sqrt((i+.5)/A)*r*.80f;float x=cx+(float)Math.cos(a)*rr,y=cy+(float)Math.sin(a)*rr*.92f;p.setColor(i<Z?Color.rgb(211,77,110):Color.rgb(116,147,173));c.drawCircle(x,y,dot,p);}p.setColor(Color.WHITE);p.setTextSize(15);c.drawText(Z+" protons • "+e.neutrons()+" neutrons",cx,cy+r+30,p);p.setColor(Color.rgb(167,195,202));p.setTextSize(12);c.drawText("Selected representative isotope",cx,cy+r+51,p);}
 private void drawIsotopes(Canvas c,float l,float t,float r,float b){panel(c,l,t,r,b,"COMMON ISOTOPES");NuclearData.Isotope[] iso=NuclearData.commonIsotopes(e.number);float y=t+68;if(iso==null){p.setColor(Color.rgb(199,217,220));p.setTextSize(14);p.setTextAlign(Paint.Align.LEFT);wrap(c,"A curated common-isotope list is not bundled for this element. The main model uses "+e.isotopeLabel()+" as its clearly labeled representative isotope.",l+28,y,r-l-56,22);return;}for(NuclearData.Isotope q:iso){p.setColor(Color.rgb(18,35,43));c.drawRoundRect(l+24,y-20,r-24,y+58,14,14,p);p.setColor(Color.WHITE);p.setTextSize(17);c.drawText(q.name,l+43,y+5,p);p.setColor(Color.rgb(125,210,220));p.setTextSize(13);c.drawText(q.abundance,l+43,y+29,p);p.setColor(Color.rgb(175,197,202));c.drawText(q.note,l+210,y+29,p);y+=91;}}
 private void drawChemistry(Canvas c,float l,float t,float r,float b){panel(c,l,t,r,b,"IONS AND COMPOUNDS");p.setTextAlign(Paint.Align.LEFT);p.setColor(Color.rgb(129,205,218));p.setTextSize(14);c.drawText("Common ionic forms",l+28,t+70,p);p.setColor(Color.WHITE);p.setTextSize(17);wrap(c,NuclearData.commonIons(e),l+28,t+101,r-l-56,24);p.setColor(Color.rgb(129,205,218));p.setTextSize(14);c.drawText("Representative compounds and materials",l+28,t+190,p);p.setColor(Color.WHITE);p.setTextSize(16);wrap(c,NuclearData.commonCompounds(e),l+28,t+221,r-l-56,24);p.setColor(Color.rgb(166,192,198));p.setTextSize(12);wrap(c,"Ion charge and oxidation state depend on the chemical environment; the examples above are educational summaries, not a complete species list.",l+28,t+316,r-l-56,19);}
 private void drawKnowledge(Canvas c,float l,float t,float r,float b){panel(c,l,t,r,b,"HOW WE KNOW");p.setTextAlign(Paint.Align.LEFT);p.setColor(Color.WHITE);p.setTextSize(16);wrap(c,"Atomic number is established by nuclear charge and characteristic X-ray spectra. Isotopes are separated and measured with mass spectrometry. Electron structure is inferred from spectroscopy, chemical behavior, and quantum-mechanical models. Nuclear size and internal structure are probed through scattering experiments and particle detectors.",l+30,t+72,r-l-60,25);p.setColor(Color.rgb(133,207,218));p.setTextSize(14);c.drawText("Why this element matters",l+30,t+192,p);p.setColor(Color.rgb(208,221,224));p.setTextSize(15);wrap(c,ScienceInfo.fact(e),l+30,t+222,r-l-60,23);p.setColor(Color.rgb(133,207,218));p.setTextSize(14);c.drawText("Scientific caution",l+30,t+290,p);p.setColor(Color.rgb(171,194,199));p.setTextSize(12);wrap(c,"The orbit rings are an educational shell model. Real electrons are described by quantum orbitals and probability distributions rather than tiny planets following fixed tracks.",l+30,t+318,r-l-60,20);}
 private void panel(Canvas c,float l,float t,float r,float b,String title){p.setColor(Color.argb(225,7,17,22));c.drawRoundRect(l,t,r,b,19,19,p);p.setStyle(Paint.Style.STROKE);p.setStrokeWidth(1.5f);p.setColor(Color.rgb(48,104,115));c.drawRoundRect(l,t,r,b,19,19,p);p.setStyle(Paint.Style.FILL);p.setColor(Color.rgb(226,210,154));p.setTextSize(19);p.setTextAlign(Paint.Align.LEFT);c.drawText(title,l+25,t+37,p);}
 private void wrap(Canvas c,String text,float x,float y,float width,float lead){String[] ws=text.split(" ");String line="";for(String q:ws){String test=line.isEmpty()?q:line+" "+q;if(p.measureText(test)>width){c.drawText(line,x,y,p);y+=lead;line=q;}else line=test;}if(!line.isEmpty())c.drawText(line,x,y,p);}
}
